version: '3'
services:
  database:
    image: mongo
    container_name: "db-consultoria"
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
  backend:
    build: .
    image: backend-consultoria
    ports:
      - 9091:8080
    depends_on:
      - database
    links:
      - database
  